name: Auto Update V2Ray Keys Every 10 Mins

on:
  schedule:
    # ၁၀ မိနစ်တစ်ကြိမ် Auto Run ခိုင်းခြင်း
    - cron: '*/5 * * * *'
  workflow_dispatch: # Manual run နိုင်ရန်

jobs:
  update-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests pytz

      - name: Run Script
        run: |
          python update_keys.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add servers
          git commit -m "Auto update servers file [skip ci]" || exit 0
          git push
